source "https://rubygems.org"

ruby '2.6.3'
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "sysrandom"

gem "minitest"
gem "rack-test"

gem 'pry'

group :production do
  gem "puma"
end